name: Run Backend Tests

on:
  push:
    branches: [main]
  pull_request:

env:
    SUPABASE_URL : ${{ secrets.SUPABASE_URL }}
    SUPABASE_KEY : ${{ secrets.SUPABASE_KEY }}
    HF_TOKEN : ${{ secrets.HF_TOKEN }}
    OPENAI_API_KEY : ${{ secrets.OPENAI_API_KEY }}
    POSTGRES_CONNECTION_STRING : ${{ secrets.POSTGRES_CONNECTION_STRING }}
    DB_RESULTS_LIMIT : "30"
    SEVERITY_WEIGHT: "0.5"
    WIDE_SCOPE_WEIGHT: "0.3"
    HIGH_IMPACT_WEIGHT: "0.2"
    IMPORTANCE_WEIGHT: "0.7"
    FRESHNESS_WEIGHT: "0.3"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest requests
      - name: Run tests
        run: PYTHONPATH=. pytest tests/